CREATE TABLE `admissao` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nome_completo` VARCHAR(255) NOT NULL,
    `nome_profissional` VARCHAR(255) NOT NULL,
    `ciencia_id` VARCHAR(100) NOT NULL,
    `orcid` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `telefone` VARCHAR(20) NOT NULL,
    `grau_academico` VARCHAR(255) NOT NULL,
    `ano_conclusao_academico` VARCHAR(255) NOT NULL,
    `area_academico` VARCHAR(255) NOT NULL,
    `area_investigacao` VARCHAR(255) NOT NULL,
    `instituicao_vinculo` VARCHAR(255) NOT NULL,
    `percentagem_dedicacao` VARCHAR(255) NOT NULL,
    `pertencer_outro` boolean NOT NULL,
    `outro_texto` TEXT,
    `biografia` TEXT NOT NULL,
    `ficheiro_motivacao` varchar(255) NOT NULL,
    `ficheiro_recomendacao` varchar(255) NOT NULL,
    `ficheiro_cv` varchar(255) NOT NULL,
    `ficheiro_fotografia` varchar(255) NOT NULL,
    `data_criacao` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;